name: PostsCountMoarFediverse

on:

  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  status:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Graphana call
        run: | 
          curl "https://fakerelay.gervas.io/index-posts-count?period=24h" \
            -H 'Authorization: Bearer ${{ secrets.FAKERELAY_APIKEY }}'

