name: PostsCountMoarFediverse

on:
  # uncomment the following 2 lines so that it runs automatically every day
  #schedule:
  #  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  PostsCount:
    runs-on: ubuntu-latest
    steps:
      - name: Graphana call
        run: | 
          curl "https://fakerelay.gervas.io/index-posts-count?period=24h" \
            -H 'Authorization: Bearer ${{ secrets.FAKERELAY_APIKEY }}'

